# Generated by Django 3.1.6 on 2021-06-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='picture',
            field=models.ImageField(max_length=255, upload_to='prop_pix/'),
        ),
    ]
