# Generated by Django 3.1.6 on 2021-06-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est_app', '0002_auto_20210620_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='picture',
            field=models.ImageField(upload_to='prop_pix/'),
        ),
    ]
