# Generated by Django 3.1.6 on 2021-06-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('est_app', '0005_auto_20210620_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadsppt', to='est_app.property'),
        ),
    ]
